### PR TITLE
exposing update_column_family api and erb parsing in cassandra.yml

### PR DESCRIPTION
**Pull request by elzoiddy**
Hi, 

I made 3 main changes to the gem.
1. Exposing update_column_family call from cassandra api. A migration can update the column family via that api.  
2. Added erb parsing to cassandra.yml.  Mainly used for getting keyspace and server info from an external source like system dependent configuration file. 
3. Added ability to disable node auto discovery in cassandra.yml if user choose to specify that. 

Let me know what you think. 

Thanks

### CODE REVIEW

**Comment by fuentesjr** [comment]
My thoughts are that this looks good except ...
1. I don't see why most people would want to use erb in cassandra.yml as a typical database.yml file in rails does not contain erb parsing (iirc) either. But this is my opinion.
2. Don't see why we need to remove .rvmrc

**Comment by elzoiddy** [comment]
1.Most people probably won't use this. But it does work in database.yml (rails 3.0.9).  Some deployment might need it, just adding the flexibility. 
1. I am adding it back, but I can go either way with this.  Maybe it should be added to .gitignore, so rvm differences won't get in the way.

**Comment by mwynholds** [comment]
Thanks elzoiddy!  I just merged in your changes, with very minor modifications.

Sorry it took me several days to get to it...

**Comment by elzoiddy** [comment]
great thanks

**Pull request closed without merging**
